### PR TITLE
Add alert toggle

### PR DESCRIPTION
**Pull request by KirkJohnson**
This creates an option in the settings page that allows alerts to either be displayed as an alert or written as console.log statements.  On a production site the error alerts could ruin user experience so this can be unchecked to give alerts without interferring with UX.

### CODE REVIEW

**Comment by garemoko** [comment]
Sounds like a very good idea.

**Comment by Jakeii** [comment]
Sorry this has gone unnoticed! The author of this plugin has been busy with other work I believe. So guess I'll be the de facto maintainer, will take a look at your pull request as soon as I can.

**Comment by greatislander** [comment]
@Jakeii Do you have any plans to release an updated version to wordpress.org in the near future?

**Comment by Jakeii** [comment]
Hi @greatislander 
I have only just got hold of the Wordpress credentials, will update the wordpress.org repo as soon as I can.

**Pull request merged**
