### PR TITLE
Add wordpress page as context activity

### PR DESCRIPTION
**Pull request by garemoko**
Addresses #1 

This has not been tested.

### CODE REVIEW

**Comment by limikael** [comment]
Awesome! Will give this a test as soon as I get a chance...

**Comment by limikael** [comment]
Merged and published in the wordpress plugin repo, version 0.0.2

Thanks alot!

**Comment by garemoko** [comment]
Thanks for merging this. I've set aside a little time for testing this afternoon and it does look like there's a typo or something because I'm getting error code 400 on my local wordpress with the updated version. I'm digging into why now.

**Comment by garemoko** [comment]
So, it looks like [this change](https://github.com/tunapanda/wp-h5p-xapi/commit/fbedfaa6f00ceb026a8548999a1651b79b9afe7e) is what's breaking things with Watershed. It shouldn't be a problem so I'll get that fixed our end. 

I also notice though that the additional context activity is not getting added to the statements, so I'll dig into why.

**Comment by limikael** [comment]
hm... but that change is only changing the version number from 0.0.1 to 0.0.2... :)

**Comment by garemoko** [comment]
Yep!

**Comment by limikael** [comment]
So changing the version number breaks it? how could that be?

btw... i made some changes here...

https://github.com/tunapanda/wp-h5p-xapi/commit/0a66bfa466a1fdad6f0d205f8065d9b356619842

sure it isn't some of those?

**Comment by garemoko** [comment]
Right now Watershed is rejecting that version number. I guess there are very few activity providers using that version number in the header. We'll get it fixed up soon enough I'm sure. Note that xAPI version 1.0.0, 1.0.1, and 1.0.2 are identical in terms of requirements. 

Turns out the issue with the context activity not getting added must have been caching. I can't replicate it again.

**Comment by limikael** [comment]
Oh I see, I changed that when I was experimenting with something else, will change it back...

Need to run for the day though, so will look at it tomorrow...

**Comment by limikael** [comment]
Ok changed the xapi version back to 1.0.1, here is the change:

https://github.com/tunapanda/wp-h5p-xapi/commit/be71322c037784367245b47d2696704b44480fbf

Will merge your other pull request as well and publish a new version to the wordpress repo.

**Pull request merged**
